from pathlib import Path

def replace(path, old, new):
    p=Path(path); text=p.read_text()
    count=text.count(old)
    if count!=1:
        raise SystemExit(f'{path}: expected one match, found {count}: {old[:100]!r}')
    p.write_text(text.replace(old,new,1))

replace('src/agency/world-model.ts',
"import { preparation, emptyTrips, type TripLearning } from './trip-logistics.ts';\nimport type { Domain, Facts, Identity, Memory, Method, Observation, Opportunity } from './types.ts';",
"import { preparation, emptyTrips, type TripLearning } from './trip-logistics.ts';\nimport { progressHealth } from './progress.ts';\nimport type { Domain, Facts, Identity, Memory, Method, Observation, Opportunity } from './types.ts';")
replace('src/agency/world-model.ts',
"export const discoveryFact = (loc:any, optionIndex:number) => `discovered:interaction:${Number(loc?.id)}:${Number(loc?.x)}:${Number(loc?.z)}:${Number(loc?.level??0)}:${optionIndex}`;\nconst discoveryCandidates = (state:LiveState,k:Knowledge) => (state.nearbyLocs??[])\n  .filter((loc:any)=>loc?.reachable===true&&Number.isInteger(loc.id)&&Number.isInteger(loc.x)&&Number.isInteger(loc.z)\n    &&(loc.optionsWithIndex??[]).some((o:any)=>/^(open|climb(?:-up|-down)?|enter|cross|use)$/i.test(String(o.text)))\n    &&!(k.discovered??{})[discoveryFact(loc,(loc.optionsWithIndex??[]).find((o:any)=>/^(open|climb(?:-up|-down)?|enter|cross|use)$/i.test(String(o.text)))!.opIndex)])\n  .sort((a:any,b:any)=>Number(a.distance??0)-Number(b.distance??0)||a.x-b.x||a.z-b.z).slice(0,8);",
"export const discoveryFact = (loc:any, optionIndex:number) => `discovered:interaction:${Number(loc?.id)}:${Number(loc?.x)}:${Number(loc?.z)}:${Number(loc?.level??0)}:${optionIndex}`;\nconst localDistance=(state:LiveState,loc:any)=>Math.max(Math.abs(Number(state.player?.worldX)-Number(loc?.x)),Math.abs(Number(state.player?.worldZ)-Number(loc?.z)));\nconst localTransition=(state:LiveState,loc:any)=>Number(loc?.level??state.player?.level??0)===Number(state.player?.level??0)\n  && (loc?.reachable===true || localDistance(state,loc)<=1);\nconst discoveryCandidates = (state:LiveState,k:Knowledge) => (state.nearbyLocs??[])\n  .filter((loc:any)=>localTransition(state,loc)&&Number.isInteger(loc.id)&&Number.isInteger(loc.x)&&Number.isInteger(loc.z)\n    &&(loc.optionsWithIndex??[]).some((o:any)=>/^(open|climb(?:-up|-down)?|enter|cross|use)$/i.test(String(o.text)))\n    &&!(k.discovered??{})[discoveryFact(loc,(loc.optionsWithIndex??[]).find((o:any)=>/^(open|climb(?:-up|-down)?|enter|cross|use)$/i.test(String(o.text)))!.opIndex)])\n  .sort((a:any,b:any)=>Number(a.distance??0)-Number(b.distance??0)||a.x-b.x||a.z-b.z).slice(0,8);")
replace('src/agency/world-model.ts',
"  for (const route of Object.values(k.routes).filter(r => meaningfulFrontierRoute(r) && r.level === Number(state.player?.level ?? 0) && !k.visited[r.id] && (!k.routeFailures?.[r.id] || k.routeFailures[r.id]!.retryAt<=now || k.routeFailures[r.id]!.context!==capabilityContext(state) || k.routeFailures[r.id]!.learningRevision<(memory.learningRevision??0))).slice(0,64))\n    add({id:'survey:'+route.id,kind:'exploration',route},'exploration','visited:'+route.id,1,1,\n       'Visit a sourced lead and verify it personally; path assessment and arrival are required.', 'frontier');\n  if (supported.includes('discovery')) {",
"  const recentLocalProbes=memory.reviews.filter(r=>r.goal.id.startsWith('local-probe:')&&now-r.at<10*60_000).length;\n  const p=state.player;\n  if(supported.includes('exploration')&&recentLocalProbes<2&&state.inGame!==false&&p&&!p.isDead&&p.combat?.inCombat!==true&&state.danger?.active!==true\n    &&[p.worldX,p.worldZ,p.level].every(Number.isFinite)&&Object.keys(k.routes).filter(id=>id.startsWith('local-probe:')).length<128) {\n    for(const [dx,dz] of [[3,0],[-3,0],[0,3],[0,-3]] as const) {\n      const x=Number(p.worldX)+dx,z=Number(p.worldZ)+dz,level=Number(p.level),id=`local-probe:${x}:${z}:${level}`;\n      if(k.routes[id]||k.visited[id])continue;\n      k.routes[id]={id,x,z,level,evidence:`fresh-local-probe:${p.lifeId}:${state.tick}; collision verification required before movement`};\n    }\n  }\n  for (const route of Object.values(k.routes).filter(r => meaningfulFrontierRoute(r) && r.level === Number(state.player?.level ?? 0) && !k.visited[r.id]\n    && (!r.id.startsWith('local-probe:')||recentLocalProbes<2)\n    && (!k.routeFailures?.[r.id] || k.routeFailures[r.id]!.retryAt<=now || k.routeFailures[r.id]!.context!==capabilityContext(state) || k.routeFailures[r.id]!.learningRevision<(memory.learningRevision??0))).slice(0,64)) {\n    const before=opportunities.length;\n    add({id:'survey:'+route.id,kind:'exploration',route},'exploration','visited:'+route.id,1,1,\n       'Visit a sourced lead and verify it personally; path assessment and arrival are required.', 'frontier');\n    if(route.id.startsWith('local-probe:')&&opportunities.length>before)opportunities.at(-1)!.priority='maintenance';\n  }\n  if (supported.includes('discovery')) {")
replace('src/agency/world-model.ts',
"        'Test a nearby reachable transition or obstruction with a bounded safe interaction, then retain only the verified result.', 'frontier');",
"        'Test a nearby observed transition or obstruction with a bounded safe interaction, then retain only the verified result.', 'frontier');")

replace('src/agency/live-adapter.ts',
"import { meaningfulFrontierRoute, reconcileDeathLoss } from './reconciliation.ts';\nimport { addAcquisition, emptyAcquisition, observeAcquisitionSources, rememberAcquisitionSources, type AcquisitionMemory, type AcquisitionHint } from './acquisition.ts';",
"import { meaningfulFrontierRoute, reconcileDeathLoss } from './reconciliation.ts';\nimport { conflictsWithQuarantine, quarantineEligible, releaseFromFreshAccounting, transactionIdentity,\n  type QuarantinedTransaction } from './transaction-quarantine.ts';\nimport { addAcquisition, emptyAcquisition, observeAcquisitionSources, rememberAcquisitionSources, type AcquisitionMemory, type AcquisitionHint } from './acquisition.ts';")
replace('src/agency/live-adapter.ts',
"  losses?:Array<{at:number;commandId:string;lifeFrom:any;lifeTo:any;lostGp:number;items:Array<{id:number|string;count:number;name?:string}>}>;\n  lastObservation?:{at:number;tick?:number;connected?:boolean;position?:{x:number;z:number;level:number}} };",
"  losses?:Array<{at:number;commandId:string;lifeFrom:any;lifeTo:any;lostGp:number;items:Array<{id:number|string;count:number;name?:string}>}>;\n  transactionQuarantine?:QuarantinedTransaction[];\n  lastObservation?:{at:number;tick?:number;connected?:boolean;position?:{x:number;z:number;level:number}} };")
replace('src/agency/live-adapter.ts',
"    this.director.memory.progress??={since:this.clock(),noProgressActions:0,recentStates:[]};\n    this.document.lastObservation={at:this.clock(),tick:state.tick,connected:state.inGame,position:state.player && {x:state.player.worldX,z:state.player.worldZ,level:state.player.level}};",
"    this.director.memory.progress??={since:this.clock(),noProgressActions:0,recentStates:[]};\n    if(this.document.transactionQuarantine?.some(q=>q.active)&&state.bank?.isOpen===true&&Array.isArray(state.bank?.items)&&Array.isArray(state.inventory)) {\n      const now=this.clock();\n      this.document.transactionQuarantine=this.document.transactionQuarantine.map(q=>releaseFromFreshAccounting(q,state,now));\n    }\n    this.document.lastObservation={at:this.clock(),tick:state.tick,connected:state.inGame,position:state.player && {x:state.player.worldX,z:state.player.worldZ,level:state.player.level}};")
replace('src/agency/live-adapter.ts',
"  pending(scope:'task'|'safety'='task'):Receipt|undefined {\n    const receipt=scope==='safety'?this.document.safetyReceipt:this.document.receipt;\n    return receipt && structuredClone(receipt);\n  }\n  /** Persist only command-scoped executor evidence, never an entire global navigation cache. */",
"  pending(scope:'task'|'safety'='task'):Receipt|undefined {\n    const receipt=scope==='safety'?this.document.safetyReceipt:this.document.receipt;\n    return receipt && structuredClone(receipt);\n  }\n  /** Preserve a historically unresolved bank mutation as audit state instead of inventing success/failure. */\n  quarantinePendingTransaction(state:LiveState,reason:string):QuarantinedTransaction|undefined {\n    const receipt=this.document.receipt,pending=this.director.memory.pending;\n    if(!receipt||receipt.scope!=='task'||!pending||pending.commandId!==receipt.commandId||pending.status!=='unknown')return;\n    const now=this.clock();\n    if(!quarantineEligible(receipt.action,receipt.before,state,receipt.startedAt,now,reason))return;\n    const identity=transactionIdentity(receipt.action,receipt.before);if(!identity)return;\n    const evidence=[`historical-command-quarantined:${receipt.commandId}`,`fresh-current-state:${state.tick}`,\n      'No historical success or failure inferred; exact command must never be replayed.',\n      'Future bank mutations for the affected item require a complete fresh bank snapshot.'];\n    const goalKey=pending.goalKey;\n    const entry:QuarantinedTransaction={at:now,commandId:receipt.commandId,type:receipt.action.type,semanticKey:identity.semanticKey,\n      itemIds:identity.itemIds,reason,evidence,goalKey,active:true};\n    this.document.transactionQuarantine=[...(this.document.transactionQuarantine??[]),entry].slice(-64);\n    delete this.director.memory.pending;delete this.document.receipt;delete this.document.route;\n    if(this.document.acquisition?.need?.parentKey===goalKey)delete this.document.acquisition.need;\n    this.document.lastCommands=[...this.document.lastCommands,receipt.commandId].slice(-128);\n    this.document.lastOutcome={at:now,commandId:receipt.commandId,type:receipt.action.type,status:'quarantined',reason,evidence};\n    if(this.director.memory.active)this.director.deferCurrent(now,'Historical bank transaction quarantined; replan only from fresh current state.',evidence);\n    this.document.blocked='Historical bank transaction quarantined; value-moving replay disabled until fresh bank accounting.';\n    this.save();return structuredClone(entry);\n  }\n  private transactionConflict(action:LiveCandidate,state:LiveState):boolean {\n    return (this.document.transactionQuarantine??[]).some(q=>conflictsWithQuarantine(q,action,state));\n  }\n  /** Persist only command-scoped executor evidence, never an entire global navigation cache. */")
replace('src/agency/live-adapter.ts',
"  eligible(action:LiveCandidate,state:LiveState):boolean {\n    let current=action;try{current=bindItems(action,state);}catch{return false;}\n    return retryAllowed(this.document.retries?.[stepKey(current,state)],this.clock(),capabilityContext(state),this.director.memory.learningRevision??0);\n  }",
"  eligible(action:LiveCandidate,state:LiveState):boolean {\n    let current=action;try{current=bindItems(action,state);}catch{return false;}\n    if(this.transactionConflict(current,state))return false;\n    return retryAllowed(this.document.retries?.[stepKey(current,state)],this.clock(),capabilityContext(state),this.director.memory.learningRevision??0);\n  }")
replace('src/agency/live-adapter.ts',
"    if(this.document.receipt||this.document.safetyReceipt)throw new Error('RECONCILE_PENDING_ACTION_FIRST');\n    action=bindItems(action,state);\n    const view=this.catalogue(state).view;",
"    if(this.document.receipt||this.document.safetyReceipt)throw new Error('RECONCILE_PENDING_ACTION_FIRST');\n    action=bindItems(action,state);\n    if(this.transactionConflict(action,state))throw new Error('TRANSACTION_QUARANTINED_UNTIL_FRESH_BANK_ACCOUNTING');\n    const view=this.catalogue(state).view;")
replace('src/agency/live-adapter.ts',
"        preparationOnlyStreak:this.director.memory.active?.preparationOnlyStreak??0},\n      goal:this.director.memory.active,pending:brief(this.pending()),safetyPending:brief(this.pending('safety')),blocked:this.document.blocked};",
"        preparationOnlyStreak:this.director.memory.active?.preparationOnlyStreak??0},\n      transactionQuarantine:(this.document.transactionQuarantine??[]).slice(-8),\n      goal:this.director.memory.active,pending:brief(this.pending()),safetyPending:brief(this.pending('safety')),blocked:this.document.blocked};")
replace('src/agency/live-adapter.ts',
"  if(action.type==='interactNpc') {\n    const npc=(state.nearbyNpcs??[]).find((n:any)=>n.index===action.fields?.npcIndex);\n    const option=(npc?.optionsWithIndex??[]).find((o:any)=>o.opIndex===action.fields?.optionIndex);\n    if(!npc||npc.reachable!==true||!option)throw new Error('FRESH_NPC_OPTION_REQUIRED');\n    if(/^attack$/i.test(String(option.text)) && (method.risk!=='bounded'||method.domain!=='combat'))throw new Error('COMBAT_REQUIRES_A_BOUNDED_COMBAT_METHOD');\n  }\n  bindItems(action,state);",
"  if(action.type==='interactNpc') {\n    const npc=(state.nearbyNpcs??[]).find((n:any)=>n.index===action.fields?.npcIndex);\n    const option=(npc?.optionsWithIndex??[]).find((o:any)=>o.opIndex===action.fields?.optionIndex);\n    if(!npc||npc.reachable!==true||!option)throw new Error('FRESH_NPC_OPTION_REQUIRED');\n    if(/^attack$/i.test(String(option.text)) && (method.risk!=='bounded'||method.domain!=='combat'))throw new Error('COMBAT_REQUIRES_A_BOUNDED_COMBAT_METHOD');\n  }\n  if(action.type==='interactLoc') {\n    const f=action.fields??{},loc=(state.nearbyLocs??[]).find((l:any)=>l.id===f.locId&&l.x===f.x&&l.z===f.z);\n    const option=(loc?.optionsWithIndex??[]).find((o:any)=>o.opIndex===f.optionIndex),p=state.player;\n    const samePlane=Number(loc?.level??p?.level??0)===Number(p?.level??0);\n    const adjacent=samePlane&&Math.max(Math.abs(Number(p?.worldX)-Number(loc?.x)),Math.abs(Number(p?.worldZ)-Number(loc?.z)))<=1;\n    if(!loc||!option||!(loc.reachable===true||adjacent))throw new Error('FRESH_LOC_OPTION_REQUIRED');\n  }\n  bindItems(action,state);")

replace('src/agent.ts',
"  const candidates=(state.nearbyLocs??[]).flatMap((loc:any)=>{\n    if(loc.reachable!==true||!Number.isInteger(loc.x)||!Number.isInteger(loc.z)||!Number.isInteger(loc.id))return [];\n    const option=(loc.optionsWithIndex??[]).find((o:any)=>/^(open|climb(?:-up|-down)?|enter|cross|use)$/i.test(String(o.text)));\n    if(!option)return [];\n    return [{loc,option,distance:Math.max(Math.abs(Number(p.worldX)-loc.x),Math.abs(Number(p.worldZ)-loc.z))}];\n  }).filter(v=>v.distance<=3)",
"  const candidates=(state.nearbyLocs??[]).flatMap((loc:any)=>{\n    if(!Number.isInteger(loc.x)||!Number.isInteger(loc.z)||!Number.isInteger(loc.id))return [];\n    const distance=Math.max(Math.abs(Number(p.worldX)-loc.x),Math.abs(Number(p.worldZ)-loc.z));\n    const samePlane=Number(loc.level??p.level??0)===Number(p.level??0);\n    if(loc.reachable!==true&&!(samePlane&&distance<=1))return [];\n    const option=(loc.optionsWithIndex??[]).find((o:any)=>/^(open|climb(?:-up|-down)?|enter|cross|use)$/i.test(String(o.text)));\n    if(!option)return [];\n    return [{loc,option,distance}];\n  }).filter(v=>v.distance<=3)")
replace('src/agent.ts',
"      if(!check.uncertain)agency.record(old.commandId,stable,verification(check));\n      else agency.retireRestartPending(scope,state,stable,check.reason??'terminal effect is no longer attributable after restart');",
"      if(!check.uncertain)agency.record(old.commandId,stable,verification(check));\n      else {\n        const retired=agency.retireRestartPending(scope,state,stable,check.reason??'terminal effect is no longer attributable after restart');\n        if(!retired&&scope==='task')agency.quarantinePendingTransaction(stable,check.reason??'historical attribution unavailable after restart');\n      }")
replace('src/agent.ts',
"      if(agency.pending()) {\n        console.log(JSON.stringify({agency:'reconciling',commandId:pending.commandId,reason:check.reason,operation:pending.action.type,action:pending.action,startedAt:pending.startedAt,source:'agency-v2.json'}));",
"      if(agency.pending()) {\n        const quarantined=agency.quarantinePendingTransaction(state,check.reason??'historical attribution unavailable');\n        if(quarantined){\n          console.log(JSON.stringify({agency:'transaction-quarantined',commandId:quarantined.commandId,reason:quarantined.reason}));\n          continue;\n        }\n        console.log(JSON.stringify({agency:'reconciling',commandId:pending.commandId,reason:check.reason,operation:pending.action.type,action:pending.action,startedAt:pending.startedAt,source:'agency-v2.json'}));")

replace('agents/advanced/src/live-policy.ts',
"  private entityAction(o: Observation, e: Entity, goal: string, intent: Intent): LiveDecision {\n    if (e.reachable !== true || distance(o.position!, e.position) > 5) {",
"  private entityAction(o: Observation, e: Entity, goal: string, intent: Intent): LiveDecision {\n    const adjacentTransition=e.kind==='object'&&!!transitionOption(e)&&e.position.plane===o.position!.plane&&distance(o.position!,e.position)<=1;\n    if ((e.reachable !== true&&!adjacentTransition) || distance(o.position!, e.position) > 5) {")
replace('agents/advanced/src/live-policy.ts',
"    const candidate=o.entities\n      .filter(e=>e.kind==='object'&&e.reachable===true&&!!transitionOption(e)\n        &&(!goal.startsWith('discover:discovered:interaction:')",
"    const candidate=o.entities\n      .filter(e=>e.kind==='object'&&!!transitionOption(e)&&e.position.plane===o.position!.plane\n        &&(e.reachable===true||distance(o.position!,e.position)<=1)\n        &&(!goal.startsWith('discover:discovered:interaction:')")

replace('agents/advanced/src/restart-journals.ts',
"    const receipt=agency.pending(scope);if(!receipt)continue;\n    const row=store.action(receipt.commandId);\n    let proof=row?arbiterVerification(receipt.commandId,row.result):{status:'unknown' as const,evidence:[],reason:'No executor receipt matched.'};",
"    const receipt=agency.pending(scope);if(!receipt)continue;\n    const row=store.action(receipt.commandId);\n    if(row?.result.reason==='HISTORICALLY_UNRESOLVED_QUARANTINED') {\n      const q=agency.quarantinePendingTransaction(agencyState(second),row.result.reason);\n      if(q){report.resolved.push(receipt.commandId);continue;}\n    }\n    let proof=row?arbiterVerification(receipt.commandId,row.result):{status:'unknown' as const,evidence:[],reason:'No executor receipt matched.'};")
replace('agents/advanced/src/restart-journals.ts',
"    agency.record(receipt.commandId,agencyState(second),proof);\n    if(agency.pending(scope))report.unresolved.push({commandId:receipt.commandId,operation:receipt.action.type,reason:proof.reason??'Pending accounting or safety outcome.'});",
"    agency.record(receipt.commandId,agencyState(second),proof);\n    if(agency.pending(scope)&&scope==='task'&&proof.status==='unknown') {\n      const q=agency.quarantinePendingTransaction(agencyState(second),proof.reason??'historical attribution unavailable');\n      if(q&&row) {\n        const administrative={...row.result,status:'CANCELLED' as const,reason:'HISTORICALLY_UNRESOLVED_QUARANTINED',at:Date.now(),evidence:q.evidence};\n        store.result(administrative);store.append('transaction_quarantine',q.commandId,q);report.resolved.push(receipt.commandId);continue;\n      }\n    }\n    if(agency.pending(scope))report.unresolved.push({commandId:receipt.commandId,operation:receipt.action.type,reason:proof.reason??'Pending accounting or safety outcome.'});")

replace('agents/advanced/src/live-cli.ts',
"          agency.record(receipt.commandId,agencyState(latest),proof);\n          if(proof.status==='interrupted'&&proof.recovery==='investigate'&&stored&&receipt.before._advanced) {",
"          agency.record(receipt.commandId,agencyState(latest),proof);\n          if(agency.pending(scope)&&scope==='task'&&proof.status==='unknown') {\n            const q=agency.quarantinePendingTransaction(agencyState(latest),proof.reason??'historical attribution unavailable');\n            if(q&&stored) {\n              store.result({...stored.result,status:'CANCELLED',reason:'HISTORICALLY_UNRESOLVED_QUARANTINED',at:Date.now(),evidence:q.evidence});\n              store.append('transaction_quarantine',q.commandId,q);\n            }\n          }\n          if(proof.status==='interrupted'&&proof.recovery==='investigate'&&stored&&receipt.before._advanced) {")

# validation retrigger after updating the route fallback regression
