import { describe, expect, test } from 'bun:test';
import { RuneMysteries, QUEST_JOURNAL, TRANSITIONS, journalStage, questDialogue } from './rune-mysteries';

const state = (extra: any = {}) => ({ inGame: true, tick: 10, player: { worldX: 3222, worldZ: 3218, level: 0, hp: 44, maxHp: 44, lifeId: 1, respawnCount: 0 },
  inventory: [{ id:315, name:'Shrimps', count:3, optionsWithIndex:[{text:'Eat',opIndex:1}]}], nearbyNpcs:[], nearbyLocs:[], ...extra });
const journal = (text: string) => state({interface: { isOpen:true, interfaceId:QUEST_JOURNAL, debugInfo:[`#1 text="@dre@Rune Mysteries"`, `#2 text=${JSON.stringify(text)}`]}});
function ready(stage: number) { const q = new RuneMysteries({character:'stinger',stage}); q.memory.needsJournal = false; return q; }
describe('Rune Mysteries observed progress', () => {
  const stages = ['I can start this quest by speaking to Duke Horacio', 'I need to find the @dre@Head Wizard@dbl@ and give him the @dre@Talisman',
    'I should talk to the Head Wizard again', 'I should take this Research Package to Aubury in Varrock',
    'I should speak to Aubury again when he has finished examining the research package', 'I should take the notes to Sedridor and see what he says', 'QUEST COMPLETE!'];
  stages.forEach((text, stage) => test(`reads public journal stage ${stage}`, () => expect(journalStage(journal(text))).toBe(stage)));
  test('ignores unrelated or unavailable journal', () => { expect(journalStage(state())).toBeUndefined(); const s=journal('QUEST COMPLETE!'); s.interface.interfaceId=123; expect(journalStage(s)).toBeUndefined(); });
  test('cannot infer completion from Runecraft level or an air talisman', () => { const q=new RuneMysteries({character:'stinger'}); const s=state({skills:[{name:'Runecraft',level:30}],inventory:[{id:1438,count:1}]}); expect(q.next(s)?.id).toBe('quest-select-tab'); expect(q.memory.completed).not.toBe(true); });
  test('rechecks journal on restart', () => { const q=new RuneMysteries({character:'stinger',stage:6,completed:true}); expect(q.next(state())?.id).toBe('quest-select-tab'); });
  test('missing health cannot authorize quest travel',()=>{const q=ready(0);q.next(state({player:{...state().player,hp:undefined}}));expect(q.memory.blocked).toBe('incomplete-quest-observation');});
  test('completion comes only from freshly read journal', () => { const q=ready(5); q.observe(state(),journal('QUEST COMPLETE!'),{id:'quest-read-journal',type:'clickComponent',waitTicks:2}); expect(q.memory.completed).toBe(true); expect(q.memory.evidence).toContain('QUEST COMPLETE!'); });
  test('Notes item id selects return to Sedridor', () => { const q=ready(5); const s=state({player:{...state().player,worldX:3104,worldZ:9576},inventory:[...state().inventory,{id:291,name:'Notes',count:1}]}); expect(q.next(s)?.id).toBe('quest-talk-sedridor'.replace('talk','approach')); });
  test('missing notes returns to Aubury', () => { const q=ready(5); const s=state({player:{...state().player,worldX:3104,worldZ:9576},nearbyLocs:[{...TRANSITIONS.towerUp.at,id:2148,reachable:true,optionsWithIndex:[{text:'Climb-up',opIndex:1}]}]}); expect(q.next(s)?.id).toBe('quest-transition-towerUp'); });
  test('wrong floor cannot talk to Duke', () => { const q=ready(0); const s=state({nearbyNpcs:[{name:'Duke Horacio',index:7,reachable:true}]}); expect(q.next(s)?.type).toBe('walkTo'); });
  test('transition requires observed exact object and option', () => { const q=ready(0); q.memory.itineraryKey='0:castle'; q.memory.itinerary=[]; const s=state({player:{...state().player,worldX:3205,worldZ:3228}}); q.next(s); expect(q.memory.blocked).toContain('transition-not-observed'); });
  test('correct transition dispatch is not arrival', () => { const q=ready(0); q.observe(state(),state(),{id:'quest-transition-castleUp',type:'interactLoc',waitTicks:6},{success:true,phase:'dispatch'}); expect(q.memory.blocked).toBe('transition-arrival-unverified'); });
  test('tower transition checks region even though plane stays zero', () => { const q=ready(1); const s=state({player:{...state().player,worldX:3104,worldZ:9576}}); q.observe(state(),s,{id:'quest-transition-towerDown',type:'interactLoc',waitTicks:6},{success:true}); expect(q.memory.blocked).toBeUndefined(); });
  test('route rejection stops instead of scanning forever', () => { const q=ready(0); q.observe(state(),state(),{id:'quest-road-castle',type:'walkTo',waitTicks:2},{navigation:{status:'blocked'}}); expect(q.memory.blocked).toContain('action-failed'); expect(q.next(state())).toBeUndefined(); });
  test('damage or respawn interrupts the quest', () => { for(const extra of [{hp:30},{lifeId:2}]) { const q=ready(0); q.observe(state(),state({player:{...state().player,...extra}}),{id:'quest-dialog',type:'clickDialogOption',waitTicks:2}); expect(q.memory.blocked).toBeDefined(); }});
  test('missing food plans free resupply before quest travel', () => { const q=ready(0); expect(q.next(state({inventory:[]}))?.id).toBe('quest-food-patch'); expect(q.memory.preparingFood).toBe(true); });
  test('full inventory remains a prerequisite', () => { const full=ready(0); full.next(state({inventory:Array(26).fill(state().inventory[0])})); expect(full.memory.blocked).toBe('quest-inventory-space-required'); });
  test('food bank deposits logs but preserves quest items and tools', () => {const q=ready(0);q.memory.preparingFood=true;const s=state({bank:{isOpen:true},inventory:[{id:291,name:'Notes',count:1,slot:0},{id:946,name:'Knife',count:1,slot:1},{id:1519,name:'Willow logs',count:1,slot:2}]});expect(q.next(s)?.fields?.slot).toBe(2);});
  test('food pickup without gain temporarily excludes that exact plant',()=>{const q=ready(0);q.observe(state(),state(),{id:'quest-pick-food',type:'interactLoc',fields:{x:3194,z:3285},waitTicks:3});expect(q.memory.foodUnavailable?.['3194,3285']).toBeGreaterThan(Date.now());});
  test('second Aubury conversation does not repeat the world circuit',()=>{const q=ready(4);const s=state({player:{...state().player,worldX:3253,worldZ:3402},nearbyNpcs:[{index:12,name:'Aubury',typeId:553,reachable:true}]});expect(q.next(s)?.id).toBe('quest-talk-aubury');});
  test('resumed damaged economy character heals before moving',()=>{const q=ready(3);const s=state({player:{...state().player,hp:8,maxHp:11},inventory:[{...state().inventory[0],slot:4},{id:290,count:1}]});expect(q.next(s)?.id).toBe('quest-recover-health');expect(q.next(s)?.fields?.slot).toBe(4);});
  test('healing dispatch is not recovery evidence',()=>{const q=ready(3);const s=state({player:{...state().player,hp:8,maxHp:11},inventory:[{...state().inventory[0],slot:4}]});q.observe(s,s,{id:'quest-recover-health',type:'useInventoryItem',fields:{slot:4},waitTicks:3});expect(q.memory.blocked).toBe('quest-healing-unverified');});
  test('restart invalidates old unsafe itinerary but retains journal milestone',()=>{const q=new RuneMysteries({character:'coincrafter',stage:3,itineraryKey:'3:aubury',itinerary:[{x:3222,z:3218,level:0}]});expect(q.memory.itineraryKey).toBeUndefined();expect(q.memory.stage).toBe(3);});
  test('tower return uses southern detour rather than bear corridor',()=>{const q=ready(3);const s=state({player:{...state().player,worldX:3105,worldZ:3162},inventory:[...state().inventory,{id:290,count:1}]});expect(q.next(s)?.fields).toMatchObject({x:3148,z:3200});});
  test('restart already inside Varrock goes north to shop, not back to Lumbridge',()=>{const q=ready(3);const s=state({player:{...state().player,worldX:3229,worldZ:3389},inventory:[...state().inventory,{id:290,count:1}]});expect(q.next(s)?.fields).toMatchObject({x:3253,z:3410});});
  test('notes holder departs north before the eastern return route',()=>{const q=ready(5);const s=state({player:{...state().player,worldX:3241,worldZ:3407},inventory:[...state().inventory,{id:291,count:1}]});expect(q.next(s)?.fields).toMatchObject({x:3238,z:3426});});
  test('unknown dialogue never picks first option', () => expect(questDialogue([{index:0,text:'Buy runes'},{index:1,text:'Attack'}])).toBeUndefined());
  test('quest dialogue resolves text, not option order', () => expect(questDialogue([{index:1,text:'Where can I find money?'},{index:8,text:'Have you any quests for me?'}])?.index).toBe(8));
  test('Aubury delivery wins over shop answer', () => expect(questDialogue([{index:1,text:'Yes please!'},{index:3,text:'I have been sent here with a package for you.'}])?.index).toBe(3));
  test('completed quest returns upstairs before handing back to normal play', () => { const q=ready(6); q.memory.completed=true; const s=state({player:{...state().player,worldX:3103,worldZ:9572}}); expect(q.next(s)?.id).toBe('quest-approach-towerUp'); expect(q.memory.returned).not.toBe(true); });
});
